- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.PERSONAL_TOKEN }}
    publish_dir: ./dist
    external_repository: Vladislav-Proshchenkov/Popover
    keep_files: true